name=lvgl_giga_squareline
version=1.0
author=Martino Facchin
category=Display
url=https://arduino.cc
architectures=*
includes=lvgl_giga_squareline.h
sentence=Giga_SquareLine
paragraph=...
name=lvgl_giga_squareline
maintainer=Squareline Studio
maintainer_email=e.voltaggio@arduino.cc

