// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#include "../ui.h"

void ui_RoomScreen_screen_init(void)
{
ui_RoomScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_RoomScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_RoomScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_RoomScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Header = lv_obj_create(ui_RoomScreen);
lv_obj_set_height( ui_Header, 80);
lv_obj_set_width( ui_Header, lv_pct(100));
lv_obj_set_x( ui_Header, -349 );
lv_obj_set_y( ui_Header, -211 );
lv_obj_set_align( ui_Header, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0xDAE3E3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Header, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Header, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LeftGroup = lv_obj_create(ui_Header);
lv_obj_set_width( ui_LeftGroup, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_LeftGroup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LeftGroup, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LeftGroup,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_LeftGroup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_LeftGroup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LeftGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LeftGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_LeftGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_LeftGroup, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Clock = lv_textarea_create(ui_LeftGroup);
lv_obj_set_width( ui_Clock, 67);
lv_obj_set_height( ui_Clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Clock, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Clock,"...");
lv_obj_set_style_text_align(ui_Clock, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Clock, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Clock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_RoomName = lv_textarea_create(ui_LeftGroup);
lv_obj_set_width( ui_RoomName, 218);
lv_obj_set_height( ui_RoomName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomName, 0 );
lv_obj_set_y( ui_RoomName, 1 );
lv_obj_set_align( ui_RoomName, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_RoomName,"Jupiter Room");
lv_textarea_set_one_line(ui_RoomName,true);
lv_obj_set_style_text_font(ui_RoomName, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomName, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_RightGroup = lv_obj_create(ui_Header);
lv_obj_set_width( ui_RightGroup, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RightGroup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RightGroup, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_RightGroup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_RightGroup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_RightGroup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RightGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RightGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_RightGroup, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_RightGroup, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LogoLabel = lv_textarea_create(ui_RightGroup);
lv_obj_set_width( ui_LogoLabel, 200);
lv_obj_set_height( ui_LogoLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LogoLabel, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_LogoLabel," powered by");
lv_textarea_set_one_line(ui_LogoLabel,true);
lv_obj_set_style_text_align(ui_LogoLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LogoLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LogoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LogoLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Logo = lv_img_create(ui_RightGroup);
lv_img_set_src(ui_Logo, &ui_img_iot_cloud_png);
lv_obj_set_width( ui_Logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Logo, 248 );
lv_obj_set_y( ui_Logo, -206 );
lv_obj_set_align( ui_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Content = lv_obj_create(ui_RoomScreen);
lv_obj_set_width( ui_Content, lv_pct(100));
lv_obj_set_flex_grow( ui_Content, 1);
lv_obj_set_x( ui_Content, 0 );
lv_obj_set_y( ui_Content, -1 );
lv_obj_set_align( ui_Content, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Content,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Content, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Booking = lv_obj_create(ui_Content);
lv_obj_set_width( ui_Booking, lv_pct(100));
lv_obj_set_height( ui_Booking, lv_pct(100));
lv_obj_set_x( ui_Booking, -1 );
lv_obj_set_y( ui_Booking, 0 );
lv_obj_set_align( ui_Booking, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Booking,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Booking, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Booking, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Booking, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Booking, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Booking, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Booking, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Booking, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Booking, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Booking, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Booking, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Booking, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BookingHeader = lv_obj_create(ui_Booking);
lv_obj_remove_style_all(ui_BookingHeader);
lv_obj_set_height( ui_BookingHeader, 50);
lv_obj_set_width( ui_BookingHeader, lv_pct(100));
lv_obj_set_align( ui_BookingHeader, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_BookingHeader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_BookingHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_BookingHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CloseBtn = lv_btn_create(ui_BookingHeader);
lv_obj_set_height( ui_CloseBtn, 50);
lv_obj_set_width( ui_CloseBtn, LV_SIZE_CONTENT);  /// 141
lv_obj_set_x( ui_CloseBtn, 94 );
lv_obj_set_y( ui_CloseBtn, -189 );
lv_obj_set_align( ui_CloseBtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CloseBtn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CloseBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_CloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CloseBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CloseBtn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CloseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CloseBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CloseBtn, lv_color_hex(0xFF3300), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CloseBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CloseBtn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CloseBtn, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CloseBtn, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CloseBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CloseBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CloseBtnLabel = lv_label_create(ui_CloseBtn);
lv_obj_set_width( ui_CloseBtnLabel, LV_SIZE_CONTENT);  /// 59
lv_obj_set_height( ui_CloseBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CloseBtnLabel, 202 );
lv_obj_set_y( ui_CloseBtnLabel, 0 );
lv_obj_set_align( ui_CloseBtnLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_CloseBtnLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_CloseBtnLabel,"CLOSE");
lv_obj_set_style_text_color(ui_CloseBtnLabel, lv_color_hex(0xFF3300), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CloseBtnLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CloseBtnLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CloseBtnLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BookingTitle = lv_textarea_create(ui_BookingHeader);
lv_obj_set_width( ui_BookingTitle, LV_SIZE_CONTENT);  /// 227
lv_obj_set_height( ui_BookingTitle, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_BookingTitle, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_BookingTitle,"Book now for");
lv_textarea_set_one_line(ui_BookingTitle,true);
lv_obj_set_style_text_align(ui_BookingTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BookingTitle, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BookingTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BookingTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Spacer = lv_btn_create(ui_BookingHeader);
lv_obj_set_width( ui_Spacer, 97);
lv_obj_set_height( ui_Spacer, 50);
lv_obj_set_x( ui_Spacer, 79 );
lv_obj_set_y( ui_Spacer, -189 );
lv_obj_set_align( ui_Spacer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Spacer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Spacer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Spacer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Spacer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Spacer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Spacer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnMatrix = lv_obj_create(ui_Booking);
lv_obj_remove_style_all(ui_BtnMatrix);
lv_obj_set_width( ui_BtnMatrix, 370);
lv_obj_set_height( ui_BtnMatrix, 130);
lv_obj_set_x( ui_BtnMatrix, 0 );
lv_obj_set_y( ui_BtnMatrix, 2 );
lv_obj_set_align( ui_BtnMatrix, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_BtnMatrix,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_BtnMatrix, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_BtnMatrix, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_BtnMatrix, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BtnMatrix, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btn4 = lv_btn_create(ui_BtnMatrix);
lv_obj_set_width( ui_Btn4, 170);
lv_obj_set_height( ui_Btn4, 50);
lv_obj_set_align( ui_Btn4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Btn4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Btn4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Btn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btn4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Btn4, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Btn4, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Btn4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Btn4, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Btn4, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Btn4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Btn4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLabel4 = lv_label_create(ui_Btn4);
lv_obj_set_width( ui_BtnLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BtnLabel4, 202 );
lv_obj_set_y( ui_BtnLabel4, 0 );
lv_obj_set_align( ui_BtnLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnLabel4,"15-30 MIN");
lv_obj_set_style_text_color(ui_BtnLabel4, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnLabel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BtnLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnLabel4, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btn3 = lv_btn_create(ui_BtnMatrix);
lv_obj_set_width( ui_Btn3, 170);
lv_obj_set_height( ui_Btn3, 50);
lv_obj_set_align( ui_Btn3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Btn3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Btn3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btn3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Btn3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Btn3, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Btn3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Btn3, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Btn3, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Btn3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Btn3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLabel3 = lv_label_create(ui_Btn3);
lv_obj_set_width( ui_BtnLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BtnLabel3, 202 );
lv_obj_set_y( ui_BtnLabel3, 0 );
lv_obj_set_align( ui_BtnLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnLabel3,"45-60 MIN");
lv_obj_set_style_text_color(ui_BtnLabel3, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BtnLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnLabel3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btn2 = lv_btn_create(ui_BtnMatrix);
lv_obj_set_width( ui_Btn2, 170);
lv_obj_set_height( ui_Btn2, 50);
lv_obj_set_align( ui_Btn2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Btn2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Btn2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Btn2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Btn2, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Btn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Btn2, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Btn2, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLabel2 = lv_label_create(ui_Btn2);
lv_obj_set_width( ui_BtnLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BtnLabel2, 202 );
lv_obj_set_y( ui_BtnLabel2, 0 );
lv_obj_set_align( ui_BtnLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnLabel2,"75-90 MIN");
lv_obj_set_style_text_color(ui_BtnLabel2, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BtnLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnLabel2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btn1 = lv_btn_create(ui_BtnMatrix);
lv_obj_set_width( ui_Btn1, 170);
lv_obj_set_height( ui_Btn1, 50);
lv_obj_set_align( ui_Btn1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Btn1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Btn1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Btn1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Btn1, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Btn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Btn1, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Btn1, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Btn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Btn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnLabel1 = lv_label_create(ui_Btn1);
lv_obj_set_width( ui_BtnLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BtnLabel1, 202 );
lv_obj_set_y( ui_BtnLabel1, 0 );
lv_obj_set_align( ui_BtnLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnLabel1,"UNTIL 11.30");
lv_obj_set_style_text_color(ui_BtnLabel1, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BtnLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnLabel1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurEv = lv_obj_create(ui_Content);
lv_obj_set_width( ui_CurEv, lv_pct(60));
lv_obj_set_height( ui_CurEv, lv_pct(100));
lv_obj_set_x( ui_CurEv, -1 );
lv_obj_set_y( ui_CurEv, -1 );
lv_obj_set_align( ui_CurEv, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CurEv,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_CurEv, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_CurEv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CurEv, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurEv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CurEv, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CurEv, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CurEv, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CurEv, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CurEv, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CurEv, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurEvTitle = lv_textarea_create(ui_CurEv);
lv_obj_set_width( ui_CurEvTitle, lv_pct(101));
lv_obj_set_height( ui_CurEvTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CurEvTitle, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CurEvTitle,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CurEvTitle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_textarea_set_placeholder_text(ui_CurEvTitle,"Trying connecting...");
lv_obj_clear_flag( ui_CurEvTitle, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_CurEvTitle, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurEvTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurEvTitle, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CurEvTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurEvTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_CurEvOrganizer = lv_textarea_create(ui_CurEv);
lv_obj_set_width( ui_CurEvOrganizer, lv_pct(100));
lv_obj_set_height( ui_CurEvOrganizer, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_CurEvOrganizer, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_CurEvOrganizer,"[Waiting for data]");
lv_textarea_set_one_line(ui_CurEvOrganizer,true);
lv_obj_add_flag( ui_CurEvOrganizer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_CurEvOrganizer, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurEvOrganizer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurEvOrganizer, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CurEvOrganizer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurEvOrganizer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_CurEvTimeEnd = lv_textarea_create(ui_CurEv);
lv_obj_set_width( ui_CurEvTimeEnd, lv_pct(100));
lv_obj_set_height( ui_CurEvTimeEnd, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_CurEvTimeEnd, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_CurEvTimeEnd,"Looking for WiFi network");
lv_textarea_set_one_line(ui_CurEvTimeEnd,true);
lv_obj_clear_flag( ui_CurEvTimeEnd, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_CurEvTimeEnd, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurEvTimeEnd, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurEvTimeEnd, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CurEvTimeEnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurEvTimeEnd, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_CancelBtn = lv_btn_create(ui_CurEv);
lv_obj_set_height( ui_CancelBtn, 50);
lv_obj_set_width( ui_CancelBtn, LV_SIZE_CONTENT);  /// 141
lv_obj_set_x( ui_CancelBtn, 94 );
lv_obj_set_y( ui_CancelBtn, -189 );
lv_obj_set_align( ui_CancelBtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CancelBtn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CancelBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_CancelBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CancelBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CancelBtn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CancelBtn, lv_color_hex(0xDA5B4A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CancelBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CancelBtn, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CancelBtn, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CancelBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CancelBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CancelBtnLabel = lv_label_create(ui_CancelBtn);
lv_obj_set_width( ui_CancelBtnLabel, LV_SIZE_CONTENT);  /// 59
lv_obj_set_height( ui_CancelBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CancelBtnLabel, 202 );
lv_obj_set_y( ui_CancelBtnLabel, 0 );
lv_obj_set_align( ui_CancelBtnLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_CancelBtnLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_CancelBtnLabel,"CANCEL RESERVATION");
lv_obj_set_style_text_color(ui_CancelBtnLabel, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CancelBtnLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CancelBtnLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CancelBtnLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BookBtn = lv_btn_create(ui_CurEv);
lv_obj_set_height( ui_BookBtn, 50);
lv_obj_set_width( ui_BookBtn, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_BookBtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_BookBtn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_BookBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_BookBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BookBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BookBtn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BookBtn, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BookBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BookBtn, 28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BookBtn, 28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BookBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BookBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BookBtnLabel = lv_label_create(ui_BookBtn);
lv_obj_set_width( ui_BookBtnLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BookBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BookBtnLabel, 202 );
lv_obj_set_y( ui_BookBtnLabel, 0 );
lv_obj_set_align( ui_BookBtnLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BookBtnLabel,"BOOK NOW");
lv_obj_set_style_text_color(ui_BookBtnLabel, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BookBtnLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BookBtnLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Next = lv_obj_create(ui_Content);
lv_obj_set_height( ui_Next, lv_pct(100));
lv_obj_set_flex_grow( ui_Next, 1);
lv_obj_set_align( ui_Next, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Next,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Next, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Next, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Next, lv_color_hex(0x008184), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Next, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Next, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Next, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Next, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NextEvTitle = lv_textarea_create(ui_Next);
lv_obj_set_width( ui_NextEvTitle, lv_pct(100));
lv_obj_set_height( ui_NextEvTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_NextEvTitle, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_NextEvTitle,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_NextEvTitle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_textarea_set_placeholder_text(ui_NextEvTitle,"Meeting Title");
lv_obj_clear_flag( ui_NextEvTitle, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_NextEvTitle, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextEvTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NextEvTitle, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NextEvTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextEvTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_NextEvOrganizer = lv_textarea_create(ui_Next);
lv_obj_set_width( ui_NextEvOrganizer, lv_pct(100));
lv_obj_set_height( ui_NextEvOrganizer, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_NextEvOrganizer, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_NextEvOrganizer,"E. Voltaggio");
lv_obj_clear_flag( ui_NextEvOrganizer, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_NextEvOrganizer, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextEvOrganizer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NextEvOrganizer, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NextEvOrganizer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextEvOrganizer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_NextGroup = lv_obj_create(ui_Next);
lv_obj_set_width( ui_NextGroup, lv_pct(100));
lv_obj_set_height( ui_NextGroup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_NextGroup, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_NextGroup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_NextGroup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_NextGroup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NextGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_NextGroup, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_NextGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_NextGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_NextGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_NextGroup, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_NextGroup, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_from = lv_textarea_create(ui_NextGroup);
lv_obj_set_width( ui_from, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_from, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_from, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_from,"from");
lv_textarea_set_one_line(ui_from,true);
lv_obj_clear_flag( ui_from, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_from, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_from, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_from, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_from, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_from, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_NextEvTimeStart = lv_textarea_create(ui_NextGroup);
lv_obj_set_width( ui_NextEvTimeStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NextEvTimeStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NextEvTimeStart, 1 );
lv_obj_set_y( ui_NextEvTimeStart, 0 );
lv_obj_set_align( ui_NextEvTimeStart, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_NextEvTimeStart,"12:00");
lv_textarea_set_one_line(ui_NextEvTimeStart,true);
lv_obj_set_style_text_color(ui_NextEvTimeStart, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextEvTimeStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NextEvTimeStart, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NextEvTimeStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextEvTimeStart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_to = lv_textarea_create(ui_NextGroup);
lv_obj_set_width( ui_to, LV_SIZE_CONTENT);  /// 27
lv_obj_set_height( ui_to, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_to, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_to,"to");
lv_textarea_set_one_line(ui_to,true);
lv_obj_set_style_text_color(ui_to, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_to, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_to, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_to, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_to, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_NextEvTimeEnd = lv_textarea_create(ui_NextGroup);
lv_obj_set_width( ui_NextEvTimeEnd, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NextEvTimeEnd, LV_SIZE_CONTENT);   /// -270
lv_obj_set_align( ui_NextEvTimeEnd, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_NextEvTimeEnd,"12:00");
lv_textarea_set_one_line(ui_NextEvTimeEnd,true);
lv_obj_set_style_text_color(ui_NextEvTimeEnd, lv_color_hex(0xF7F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextEvTimeEnd, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NextEvTimeEnd, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NextEvTimeEnd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextEvTimeEnd, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



}
