// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCurevendChange();
void onCurevidChange();
void onCurevmsgChange();
void onCurevorganizerChange();
void onCurevstartChange();
void onCurevtmChange();
void onNextevendChange();
void onNextevidChange();
void onNextevmsgChange();
void onNextevorganizerChange();
void onNextevstartChange();
void onNextevtmChange();
void onRoomNameChange();
void onRoomNameApiChange();
void onBusynowChange();

String curevend;
String curevid;
String curevmsg;
String curevorganizer;
String curevstart;
String curevtm;
String nextevend;
String nextevid;
String nextevmsg;
String nextevorganizer;
String nextevstart;
String nextevtm;
String room_name;
String room_name_api;
int busynow;

void initProperties(){

  ArduinoCloud.addProperty(curevend, READWRITE, ON_CHANGE, onCurevendChange);
  ArduinoCloud.addProperty(curevid, READWRITE, ON_CHANGE, onCurevidChange);
  ArduinoCloud.addProperty(curevmsg, READWRITE, ON_CHANGE, onCurevmsgChange);
  ArduinoCloud.addProperty(curevorganizer, READWRITE, ON_CHANGE, onCurevorganizerChange);
  ArduinoCloud.addProperty(curevstart, READWRITE, ON_CHANGE, onCurevstartChange);
  ArduinoCloud.addProperty(curevtm, READWRITE, ON_CHANGE, onCurevtmChange);
  ArduinoCloud.addProperty(nextevend, READWRITE, ON_CHANGE, onNextevendChange);
  ArduinoCloud.addProperty(nextevid, READWRITE, ON_CHANGE, onNextevidChange);
  ArduinoCloud.addProperty(nextevmsg, READWRITE, ON_CHANGE, onNextevmsgChange);
  ArduinoCloud.addProperty(nextevorganizer, READWRITE, ON_CHANGE, onNextevorganizerChange);
  ArduinoCloud.addProperty(nextevstart, READWRITE, ON_CHANGE, onNextevstartChange);
  ArduinoCloud.addProperty(nextevtm, READWRITE, ON_CHANGE, onNextevtmChange);
  ArduinoCloud.addProperty(room_name, READWRITE, ON_CHANGE, onRoomNameChange);
  ArduinoCloud.addProperty(room_name_api, READWRITE, ON_CHANGE, onRoomNameApiChange);
  ArduinoCloud.addProperty(busynow, READWRITE, ON_CHANGE, onBusynowChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
