// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_RoomScreen
void ui_RoomScreen_screen_init(void);
lv_obj_t *ui_RoomScreen;
lv_obj_t *ui_Header;
lv_obj_t *ui_LeftGroup;
lv_obj_t *ui_Clock;
lv_obj_t *ui_RoomName;
lv_obj_t *ui_RightGroup;
lv_obj_t *ui_LogoLabel;
lv_obj_t *ui_Logo;
lv_obj_t *ui_Content;
lv_obj_t *ui_Booking;
lv_obj_t *ui_BookingHeader;
lv_obj_t *ui_CloseBtn;
lv_obj_t *ui_CloseBtnLabel;
lv_obj_t *ui_BookingTitle;
lv_obj_t *ui_Spacer;
lv_obj_t *ui_BtnMatrix;
lv_obj_t *ui_Btn4;
lv_obj_t *ui_BtnLabel4;
lv_obj_t *ui_Btn3;
lv_obj_t *ui_BtnLabel3;
lv_obj_t *ui_Btn2;
lv_obj_t *ui_BtnLabel2;
lv_obj_t *ui_Btn1;
lv_obj_t *ui_BtnLabel1;
lv_obj_t *ui_CurEv;
lv_obj_t *ui_CurEvTitle;
lv_obj_t *ui_CurEvOrganizer;
lv_obj_t *ui_CurEvTimeEnd;
lv_obj_t *ui_CancelBtn;
lv_obj_t *ui_CancelBtnLabel;
lv_obj_t *ui_BookBtn;
lv_obj_t *ui_BookBtnLabel;
lv_obj_t *ui_Next;
lv_obj_t *ui_NextEvTitle;
lv_obj_t *ui_NextEvOrganizer;
lv_obj_t *ui_NextGroup;
lv_obj_t *ui_from;
lv_obj_t *ui_NextEvTimeStart;
lv_obj_t *ui_to;
lv_obj_t *ui_NextEvTimeEnd;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_basic_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_RoomScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_RoomScreen);
}
