// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#ifndef _SQUARELINE_PROJECT2_UI_H
#define _SQUARELINE_PROJECT2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_RoomScreen
void ui_RoomScreen_screen_init(void);
extern lv_obj_t *ui_RoomScreen;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_LeftGroup;
extern lv_obj_t *ui_Clock;
extern lv_obj_t *ui_RoomName;
extern lv_obj_t *ui_RightGroup;
extern lv_obj_t *ui_LogoLabel;
extern lv_obj_t *ui_Logo;
extern lv_obj_t *ui_Content;
extern lv_obj_t *ui_Booking;
extern lv_obj_t *ui_BookingHeader;
extern lv_obj_t *ui_CloseBtn;
extern lv_obj_t *ui_CloseBtnLabel;
extern lv_obj_t *ui_BookingTitle;
extern lv_obj_t *ui_Spacer;
extern lv_obj_t *ui_BtnMatrix;
extern lv_obj_t *ui_Btn4;
extern lv_obj_t *ui_BtnLabel4;
extern lv_obj_t *ui_Btn3;
extern lv_obj_t *ui_BtnLabel3;
extern lv_obj_t *ui_Btn2;
extern lv_obj_t *ui_BtnLabel2;
extern lv_obj_t *ui_Btn1;
extern lv_obj_t *ui_BtnLabel1;
extern lv_obj_t *ui_CurEv;
extern lv_obj_t *ui_CurEvTitle;
extern lv_obj_t *ui_CurEvOrganizer;
extern lv_obj_t *ui_CurEvTimeEnd;
extern lv_obj_t *ui_CancelBtn;
extern lv_obj_t *ui_CancelBtnLabel;
extern lv_obj_t *ui_BookBtn;
extern lv_obj_t *ui_BookBtnLabel;
extern lv_obj_t *ui_Next;
extern lv_obj_t *ui_NextEvTitle;
extern lv_obj_t *ui_NextEvOrganizer;
extern lv_obj_t *ui_NextGroup;
extern lv_obj_t *ui_from;
extern lv_obj_t *ui_NextEvTimeStart;
extern lv_obj_t *ui_to;
extern lv_obj_t *ui_NextEvTimeEnd;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_iot_cloud_png);   // assets/Iot Cloud.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
