// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project2

#include "../ui.h"


// COMPONENT Header

lv_obj_t *ui_Header_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Header;
cui_Header = lv_obj_create(comp_parent);
lv_obj_set_height( cui_Header, 80);
lv_obj_set_width( cui_Header, lv_pct(100));
lv_obj_set_x( cui_Header, 1 );
lv_obj_set_y( cui_Header, lv_pct(0) );
lv_obj_set_align( cui_Header, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Header,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_Header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_Header, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Header, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label1;
cui_Label1 = lv_label_create(cui_Header);
lv_obj_set_width( cui_Label1, lv_pct(30));
lv_obj_set_height( cui_Label1, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( cui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label1,"Venus Room");
lv_obj_set_style_text_align(cui_Label1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Panel5;
cui_Panel5 = lv_obj_create(cui_Header);
lv_obj_set_height( cui_Panel5, 50);
lv_obj_set_width( cui_Panel5, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( cui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Panel5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Panel5, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label2;
cui_Label2 = lv_label_create(cui_Panel5);
lv_obj_set_width( cui_Label2, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( cui_Label2, LV_SIZE_CONTENT);   /// 31
lv_obj_set_align( cui_Label2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Label2,LV_FLEX_FLOW_ROW_WRAP_REVERSE);
lv_obj_set_flex_align(cui_Label2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(cui_Label2,"powered by");
lv_obj_set_style_text_align(cui_Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Image2;
cui_Image2 = lv_img_create(cui_Panel5);
lv_img_set_src(cui_Image2, &ui_img_iot_cloud_png);
lv_obj_set_width( cui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Image2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Image2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_Image2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( cui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
children[UI_COMP_HEADER_HEADER] = cui_Header;
children[UI_COMP_HEADER_LABEL1] = cui_Label1;
children[UI_COMP_HEADER_PANEL5] = cui_Panel5;
children[UI_COMP_HEADER_PANEL5_LABEL2] = cui_Label2;
children[UI_COMP_HEADER_PANEL5_IMAGE2] = cui_Image2;
lv_obj_add_event_cb(cui_Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Header_create_hook(cui_Header);
return cui_Header; 
}

