#include "arduino_secrets.h"
#include <FTDebouncer.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "blue_room"
  https://create.arduino.cc/cloud/things/2b9f21ab-3d23-4266-9188-33caadc56c2f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String curevend;
  String curevmsg;
  String curevstart;
  String curevtm;
  String nextevend;
  String nextevmsg;
  String nextevstart;
  String nextevtm;
  int busynow;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

/*

To switch between using an Arduino MKR IoT Kit or an M5 Paper
uncomment the required #define line and comment the one you
are not interested in

*/


//#define USE_MKR_IOT_CARRIER
#define USE_M5STACK_PAPER

#ifdef USE_MKR_IOT_CARRIER

#define PIN_PREV 3
#define PIN_PRESS 4
#define PIN_NEXT 5
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

#elif defined(USE_M5STACK_PAPER)

#include <M5EPD.h>
#include "FreeMonoBold32pt7b.h"
#define FMB32 &FreeMonoBold32pt7b
M5EPD_Canvas canvas(&M5.EPD);

#define PIN_PREV 37
#define PIN_PRESS 38
#define PIN_NEXT 39

#endif

#include "thingProperties.h"

FTDebouncer deb;

unsigned long cntr = 0;
unsigned long lastTickTime;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  while(!Serial && millis() < 5000){
    // wait for Serial or TimeOut
  }

  Serial.println("starting setup");
  
  /*  FT Debouncer detects button clicks and triggers callbacks
      onPinActivated(int _pin);
      onPinDeactivated(int _pin);
  */
  deb.addPin(PIN_PREV, HIGH, INPUT_PULLUP); // previous
  deb.addPin(PIN_PRESS, HIGH, INPUT_PULLUP); // press
  deb.addPin(PIN_NEXT, HIGH, INPUT_PULLUP); // next
  deb.begin();
  
  initProperties();

  /* initialise Arduino IoT Cloud instance */
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /* add CallBacks for IoT Cloud events */
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::CONNECT, doThisOnConnect);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::SYNC, doThisOnSync);
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, doThisOnDisconnect);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  delay(500);

/* Initialise MKR IoT Carrier */

#ifdef USE_MKR_IOT_CARRIER
  CARRIER_CASE = false;
  carrier.begin();
  carrier.display.setRotation(0);
  delay(1500);
#endif

/* Initialise M5 Stack Paper */
#ifdef USE_M5STACK_PAPER
  M5.begin();
  M5.EPD.SetRotation(0);
  M5.EPD.Clear(true);
  M5.RTC.begin();
  M5.SHT30.Begin();
  canvas.createCanvas(960, 540);
  canvas.useFreetypeFont(false);
  canvas.setFreeFont(FMB32);
  canvas.drawString("Hello, Meeting Room", 10, 10);
  canvas.pushCanvas(0,0,UPDATE_MODE_GC16 );
#endif

  lastTickTime = millis();
}

void loop() {
  deb.update();
  ArduinoCloud.update();
  
}

void displayUpdate() {
  Serial.println("display update");
  Serial.println(curevmsg);
#ifdef USE_MKR_IOT_CARRIER
  if (busynow) {
    carrier.display.fillScreen(0xF81F); //red background
  }
  else {
    carrier.display.fillScreen(0x051A); //red background
  }
  carrier.display.setTextColor(ST77XX_WHITE); //yellow text
  carrier.display.setTextSize(2); //medium sized text
  carrier.display.setCursor(40, 100);
  carrier.display.print(curevmsg);
  carrier.display.setCursor(40, 130);
  carrier.display.print(curevtm);
#endif
#ifdef USE_M5STACK_PAPER
  M5.EPD.Clear(true);
  canvas.drawString(curevmsg, 10, 72);
  canvas.drawString(nextevmsg, 10, 142);
  canvas.pushCanvas(0,0,UPDATE_MODE_GC16 );
#endif
}
   
void onPinActivated(int _pinNr){
  Serial.print("Pressed: ");
  Serial.println(_pinNr);
}

void onPinDeactivated(int _pinNr){
  Serial.print("Released: ");
  Serial.println(_pinNr);
}


void doThisOnConnect(){
  Serial.println("IoT Cloud Device Connected");
}

void doThisOnSync(){
  Serial.println("IoT Cloud Device Synced");

  displayUpdate();
}

void doThisOnDisconnect(){
  Serial.println("IoT Cloud Device Disconnected");
}

/*
  Since Curevmsg is READ_WRITE variable, onCurevmsgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurevmsgChange()  {
  // Add your code here to act upon Curevmsg change
  displayUpdate();
}


/*
  Since Busynow is READ_WRITE variable, onBusynowChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBusynowChange()  {
  // Add your code here to act upon Busynow change
  if(reserveAction){
    reserveAction = false;
  }
  displayUpdate();
}

/*
  Since Curevstart is READ_WRITE variable, onCurevstartChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurevstartChange()  {
  // Add your code here to act upon Curevstart change
  displayUpdate();
}

/*
  Since Curevend is READ_WRITE variable, onCurevendChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurevendChange()  {
  // Add your code here to act upon Curevend change
  displayUpdate();
}

/*
  Since Curevtm is READ_WRITE variable, onCurevtmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurevtmChange()  {
  // Add your code here to act upon Curevtm change
  displayUpdate();
}

/*
  Since Nextevmsg is READ_WRITE variable, onNextevmsgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onNextevmsgChange()  {
  // Add your code here to act upon Nextevmsg change
  displayUpdate();
}

/*
  Since Nextevstart is READ_WRITE variable, onNextevstartChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onNextevstartChange()  {
  // Add your code here to act upon Nextevstart change
  displayUpdate();
}

/*
  Since Nextevend is READ_WRITE variable, onNextevendChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onNextevendChange()  {
  // Add your code here to act upon Nextevend change
  displayUpdate();
}

/*
  Since Nextevtm is READ_WRITE variable, onNextevtmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onNextevtmChange()  {
  // Add your code here to act upon Nextevtm change
  displayUpdate();
}

void onReserveActionChange(){
  Serial.print("Reserve Action: ");
  Serial.println(reserveAction ? "ON" : "OFF");

}