// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

#ifdef USE_M5STACK_PAPER
const char DEVICE_LOGIN_NAME[]  = "83e488c3-b2c3-4ee3-983d-f14e3eaa16b3";
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
#endif

void onCurevendChange();
void onCurevmsgChange();
void onCurevstartChange();
void onCurevtmChange();
void onNextevendChange();
void onNextevmsgChange();
void onNextevstartChange();
void onNextevtmChange();
void onBusynowChange();
void onTestVarChange();
void onReserveActionChange();

String curevend;
String curevmsg;
String curevstart;
String curevtm;
String nextevend;
String nextevmsg;
String nextevstart;
String nextevtm;
int busynow;
bool testVar;
bool reserveAction;

void initProperties(){
#ifdef USE_M5STACK_PAPER
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
#endif
  ArduinoCloud.addProperty(curevend, READWRITE, ON_CHANGE, onCurevendChange);
  ArduinoCloud.addProperty(curevmsg, READWRITE, ON_CHANGE, onCurevmsgChange);
  ArduinoCloud.addProperty(curevstart, READWRITE, ON_CHANGE, onCurevstartChange);
  ArduinoCloud.addProperty(curevtm, READWRITE, ON_CHANGE, onCurevtmChange);
  ArduinoCloud.addProperty(nextevend, READWRITE, ON_CHANGE, onNextevendChange);
  ArduinoCloud.addProperty(nextevmsg, READWRITE, ON_CHANGE, onNextevmsgChange);
  ArduinoCloud.addProperty(nextevstart, READWRITE, ON_CHANGE, onNextevstartChange);
  ArduinoCloud.addProperty(nextevtm, READWRITE, ON_CHANGE, onNextevtmChange);
  ArduinoCloud.addProperty(busynow, READWRITE, ON_CHANGE, onBusynowChange);
  ArduinoCloud.addProperty(reserveAction, READWRITE, ON_CHANGE, onReserveActionChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
